version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: vendas-online-backend-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vendas-online-backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 26032020Red#
     